server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass https://media-monitor-production-2667.up.railway.app/api/;
        proxy_set_header Host media-monitor-production-2667.up.railway.app;
        proxy_ssl_server_name on;
    }

    location /ws {
        proxy_pass https://media-monitor-production-2667.up.railway.app/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host media-monitor-production-2667.up.railway.app;
        proxy_ssl_server_name on;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
# cache bust Wed Mar 11 01:12:28 +03 2026
